export const CHARACTERS = [
  { id: 'yulia', name: 'Юля', phrase: 'думайте! думайте!', height: 0.85, bodyBuild: 'slim', gender: 'female', hairColor: 0x1a1a1a, hairStyle: 'short', skinColor: 0xf5c6a0, shirtColor: 0x6a5acd, faceType: 'sharp', hasBeard: false, beardColor: null, seatAngle: 0 },
  { id: 'arsen', name: 'Арсен', phrase: 'в этой песне по другому поётся!!', height: 1.15, bodyBuild: 'stocky', gender: 'male', hairColor: 0x2d1b0e, hairStyle: 'short', skinColor: 0xe8b887, shirtColor: 0x2e8b57, faceType: 'round', hasBeard: false, beardColor: null, seatAngle: 36 },
  { id: 'tanya', name: 'Таня', phrase: 'ща буду шутить', height: 1.0, bodyBuild: 'medium', gender: 'female', hairColor: 0xcc4400, hairStyle: 'long', skinColor: 0xf5c6a0, shirtColor: 0xff6347, faceType: 'round', hasBeard: false, beardColor: null, seatAngle: 72 },
  { id: 'katya', name: 'Катя', phrase: 'хороший стол в этот раз накрыли!', height: 1.0, bodyBuild: 'medium', gender: 'female', hairColor: 0xf0d58c, hairStyle: 'medium', skinColor: 0xf5c6a0, shirtColor: 0x4682b4, faceType: 'round', hasBeard: false, beardColor: null, seatAngle: 108 },
  { id: 'alena', name: 'Алена', phrase: 'музыкальный блок я вам точно выиграю', height: 0.9, bodyBuild: 'slim', gender: 'female', hairColor: 0x6b4226, hairStyle: 'medium', skinColor: 0xf5c6a0, shirtColor: 0xda70d6, faceType: 'round', hasBeard: false, beardColor: null, seatAngle: 144 },
  { id: 'anya', name: 'Аня', phrase: 'Да! Да! Точно!', height: 1.1, bodyBuild: 'medium', gender: 'female', hairColor: 0x1a1a1a, hairStyle: 'long', skinColor: 0xf0d5a0, shirtColor: 0xff69b4, faceType: 'asian', hasBeard: false, beardColor: null, seatAngle: 180 },
  { id: 'sasha', name: 'Саша', phrase: 'полетели как сдурели!', height: 1.0, bodyBuild: 'stocky', gender: 'male', hairColor: 0x2d1b0e, hairStyle: 'short', skinColor: 0xf5c6a0, shirtColor: 0x556b2f, faceType: 'round', hasBeard: true, beardColor: 0xcc4400, seatAngle: 216 },
  { id: 'olya', name: 'Оля', phrase: 'телефон мой жирными руками не трогать!', height: 1.1, bodyBuild: 'medium', gender: 'female', hairColor: 0x2d1b0e, hairStyle: 'long', skinColor: 0xf5c6a0, shirtColor: 0x708090, faceType: 'round', hasBeard: false, beardColor: null, seatAngle: 252 },
  { id: 'rus', name: 'Рус', phrase: 'Некорректный вопрос!', height: 0.9, bodyBuild: 'medium', gender: 'male', hairColor: 0x2d1b0e, hairStyle: 'short', skinColor: 0xf5c6a0, shirtColor: 0x8b4513, faceType: 'round', hasBeard: false, beardColor: null, seatAngle: 288 },
  { id: 'denis', name: 'Денис', phrase: 'Доверьтесь мне!', height: 1.0, bodyBuild: 'medium', gender: 'male', hairColor: 0x2d1b0e, hairStyle: 'short', skinColor: 0xf5c6a0, shirtColor: 0x4169e1, faceType: 'round', hasBeard: true, beardColor: 0x1a1a1a, seatAngle: 324 }
];
